# Generated by Django 3.1.5 on 2021-01-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa substancji')),
                ('measure', models.CharField(choices=[('kg', 'kg'), ('l', 'l')], max_length=8, verbose_name='Jednostka miary')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa odbiorcy gotowego produktu')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa dostawcy')),
                ('comment', models.TextField(verbose_name='Uwagi')),
                ('component', models.ManyToManyField(to='stocklevel_app.Component', verbose_name='Substancja dostarczana przez dostawcę')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Ilość')),
                ('measure', models.CharField(choices=[('kg', 'kg'), ('l', 'l')], max_length=8, verbose_name='Jednostka miary')),
                ('purpose', models.CharField(choices=[('badania', 'badania'), ('produkcja', 'produkcja'), ('usunięcie', 'usunięcie')], max_length=24, verbose_name='Cel wydania materiału')),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Data wydania materiału')),
                ('component', models.ManyToManyField(to='stocklevel_app.Component')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Ilość')),
                ('supplier_series_number', models.CharField(max_length=100, verbose_name='Numer serii producenta')),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('warehouse_series_number', models.CharField(max_length=100, verbose_name='Numer magazynowy')),
                ('laboratory_series_number', models.CharField(max_length=100, null=True, verbose_name='Numer serii po badaniu')),
                ('use_by_date', models.DateField(verbose_name='Termin przydatności')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocklevel_app.component')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocklevel_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa produktu')),
                ('production_start', models.DateField(verbose_name='Rozpoczęcie produkcji')),
                ('production_finish', models.DateField(verbose_name='Zakończenie produkcji')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocklevel_app.recipient', verbose_name='Odbiorca produktu')),
            ],
        ),
    ]
