# Generated by Django 3.1.5 on 2021-02-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklevel_app', '0005_auto_20210201_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseflows',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Data wydania z magazynu'),
        ),
    ]
