# Generated by Django 3.1.5 on 2021-01-31 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocklevel_app', '0003_auto_20210128_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('n', 'n')], default='n', max_length=1, verbose_name='Kategoria dostawcy'),
        ),
        migrations.AddField(
            model_name='warehouseentry',
            name='laboratory_series_date',
            field=models.DateField(null=True, verbose_name='Data wykonania badania'),
        ),
        migrations.AlterField(
            model_name='warehouseentry',
            name='delivery_date',
            field=models.DateField(verbose_name='Data wpływu materiału'),
        ),
        migrations.AlterField(
            model_name='warehouseentry',
            name='warehouse_series_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Numer magazynowy'),
        ),
        migrations.AlterField(
            model_name='warehouserelease',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocklevel_app.component', verbose_name='Nazwa materiału wyjściowego'),
        ),
        migrations.AlterField(
            model_name='warehouserelease',
            name='release_date',
            field=models.DateField(verbose_name='Data wydania materiału'),
        ),
    ]
