# Generated by Django 3.1.5 on 2021-02-01 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocklevel_app', '0004_auto_20210131_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseFlows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Ilość')),
                ('supplier_series_number', models.CharField(max_length=100, verbose_name='Numer serii producenta')),
                ('delivery_date', models.DateField(verbose_name='Data wpływu materiału')),
                ('warehouse_series_number', models.CharField(max_length=100, unique=True, verbose_name='Numer magazynowy')),
                ('use_by_date', models.DateField(verbose_name='Termin przydatności')),
                ('laboratory_series_date', models.DateField(null=True, verbose_name='Data wykonania badania')),
                ('laboratory_series_number', models.CharField(help_text='Pole do uzupełnienia po wykonaniu badań wewnętrznych', max_length=100, null=True, verbose_name='Numer serii po badaniu')),
                ('release_date', models.DateField(verbose_name='Data wydania z magazynu')),
                ('release_purpose', models.CharField(choices=[('badania', 'badania'), ('produkcja', 'produkcja'), ('usunięcie', 'usunięcie')], max_length=24, null=True, verbose_name='Cel wydania materiału')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocklevel_app.component', verbose_name='Nazwa materiału wyjściowego')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocklevel_app.supplier', verbose_name='Dostawca materiału')),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouserelease',
            name='component',
        ),
        migrations.DeleteModel(
            name='WarehouseEntry',
        ),
        migrations.DeleteModel(
            name='WarehouseRelease',
        ),
    ]
